version: '3.1'

services:
  app:
    image: '9cd53486dff8'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=YOURPASSWORD
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=W200505t